
CREATE TABLE eg_mr_marriageregistration_migration (
	id character varying(64) NOT NULL,
	tenantid character varying(64) NOT NULL,
	ulbname character varying(64),
	registrationno character varying(64),
	applicationno character varying(64),
	dateofapplication bigint,
	dateofregistration bigint,
	approvedby character varying(256),
	placeofapproval character varying(256),
	currentstatus character varying(256),
	marriageward character varying(256),
	marriagezone character varying(256),
	placeofmarriage character varying(256),
	bridetitle character varying(64),
	bridefirstname character varying(256),
	bridemiddlename character varying(256),
	bridelastname character varying(256),
	bridefathertitle character varying(64),
	bridefatherfirstname character varying(256),
	bridefathermiddlename character varying(256),
	bridefatherlastname character varying(256),
	bridemothertitle character varying(64),
	bridemotherfirstname character varying(256),
	bridemothermiddlename character varying(256),
	bridemotherlastname character varying(256),
	bridecontact character varying(64),
	brideemailaddress character varying(256),
	isbridedivyang character varying(64),
	groomtitle character varying(64),
	groomfirstname character varying(256),
	groommiddlename character varying(256),
	groomlastname character varying(256),
	groomfathertitle character varying(64),
	groomfatherfirstname character varying(256),
	groomfathermiddlename character varying(256),
	groomfatherlastname character varying(256),
	groommothertitle character varying(64),
	groommotherfirstname character varying(256),
	groommothermiddlename character varying(256),
	groommotherlastname character varying(256),
	groomcontact character varying(64),
	groomemailaddress character varying(256),
	isgroomdivyang character varying(64),
	brideaddressline1 character varying(256),
	brideaddressline2 character varying(256),
	brideaddressline3 character varying(256),
	bridecountry character varying(256),
	bridestate character varying(256),
	bridedistrict character varying(256),
	bridepincode character varying(64),
	bridedateofbirth bigint,
	brideage character varying(64),
	brideguardianrelationship character varying(256),
	brideguardianname character varying(256),
	brideguardianaddressline1 character varying(256),
	brideguardianaddressline2 character varying(256),
	brideguardianaddressline3 character varying(256),
	brideguardiancontact character varying(64),
	brideguardiancountry character varying(256),
	brideguardianstate character varying(256),
	brideguardiandistrict character varying(256),
	brideguardianemail character varying(256),
	brideguardianpin character varying(64),
	groomaddressline1 character varying(256),
	groomaddressline2 character varying(256),
	groomaddressline3 character varying(256),
	groomcountry character varying(256),
	groomstate character varying(256),
	groomdistrict character varying(256),
	groompincode character varying(64),
	groomdateofbirth bigint,
	groomage character varying(64),
	groomguardianrelationship character varying(256),
	groomguardianname character varying(256),
	groomguardianaddressline1 character varying(256),
	groomguardianaddressline2 character varying(256),
	groomguardianaddressline3 character varying(256),
	groomguardiancountry character varying(256),
	groomguardianstate character varying(256),
	groomguardiandistrict character varying(256),
	groomguardianemail character varying(256),
	groomguardianpin character varying(64),
	witness1title character varying(64),
	witness1address character varying(256),
	witness1contact character varying(64),
	witness1country character varying(256),
	witness1state character varying(256),
	witness1district character varying(256),
	witness1pin character varying(64),
	witness1firstname character varying(256),
	witness1middlename character varying(256),
	witness1lastname character varying(256),
	witness2title character varying(64),
	witness2address character varying(256),
	witness2contact character varying(64),
	witness2country character varying(256),
	witness2state character varying(256),
	witness2district character varying(256),
	witness2pin character varying(64),
	witness2firstname character varying(256),
	witness2middlename character varying(256),
	witness2lastname character varying(256),
	createdtime bigint,
	
	CONSTRAINT uk_eg_marriageregistration_migration UNIQUE (id)
);


